version: '3.7'

secrets:
  discord_token:
    external: true

services:
  server:
    build: 
      context: ./discord_bot
      dockerfile: Dockerfile
    volumes:
      - ./discord_bot/:/discord_bot/
    command: python3 bot.py
    secrets:
      -  discord_token